# frozen_string_literal: true

source 'https://www.rubygems.org'

gem 'activesupport'
gem 'airborne'
gem 'aws-sdk'
gem 'capybara'
gem 'chromedriver-helper'
gem 'chronic'
gem 'cucumber', '>= 3'
gem 'curb'
gem 'dotenv-rails', require: 'dotenv'
gem 'faker'
gem 'nokogiri'
gem 'pry'
gem 'rake'
gem 'report_builder'
gem 'require_all'
gem 'rspec'
gem 'rspec-retry'
gem 'rubocop'
gem 'sauce_whisk'
gem 'selenium-webdriver'
gem 'viewpoint'
gem 'webmock'
